# ------ root_path/dataset_name ------
root_path: "Your Dataset Path"

# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparamters ------
init_beta: 72.00
init_alpha: 1.66
T: 1

# ------ Basic Config ------
dataset: 'ImageNet'
shots: 1
backbone: 'RN50'
lr: 0.0005
augment_epoch: 1

seed: 1