# ------ root_path/dataset_name ------
root_path: '/data/yic/Tip-Adapter-main/data/data'

# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparamters ------
init_beta: 26
init_alpha: 1
T: 1

# ------ Basic Config ------
dataset: 'oxford-pet'
shots: 1
backbone: 'RN50'
lr: 0.0001
augment_epoch: 10

seed: 1