# ------ root_path/dataset_name ------
root_path: "Your Dataset Path"

# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparamters ------
init_beta: 43.57
init_alpha: 1.18
T: 1

# ------ Basic Config ------
dataset: 'sun397'
shots: 1
backbone: 'RN50'
lr: 0.001
augment_epoch: 20

seed: 1